### ISSUE TITLE
welink、蓝信等平台开发的PC小程序中不显示devtools，但是在对应平台的手机上的相应小程序可以显示devtools

### ISSUE THREAD

**Issue by wangran99** [Zippowxk/vue-vconsole-devtools#12]
welink pc端、手机端小程序html代码：
```
<div id="app"></div>
    <script src="https://open-doc.welink.huaweicloud.com/docs/jsapi/2.0.6/hwh5-cloudonline.js"></script>
    <script src="https://unpkg.com/vconsole/dist/vconsole.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-vconsole-devtools@1.0.5/dist/vue_plugin.js"></script>
    <script>
      var vConsole = new window.VConsole();
      const Devtools = window.vueVconsoleDevtools
      Devtools.initPlugin(vConsole);
    </script>
```
pc端截图：
![image](https://user-images.githubusercontent.com/17898332/141405881-43fe7be8-3de3-47c6-bea6-9a0e6e82c626.png)
手机端截图：
![2bbb5dbcec6a5ccdcd81e85b70f8f05](https://user-images.githubusercontent.com/17898332/141406110-70e6b719-9650-4d48-836e-c7df24bc80b2.jpg)

为什么会导致在welink、蓝信这类平台中的pc端小程序devtools失效，钉钉平台没试过。希望有回复，谢谢。

**Comment by Zippowxk** [comment]
这个可能和环境有关，之前验证时没涉及这两个平台，需要配置环境来Debug

**Comment by wangran99** [comment]
这个插件真的很有用，未来版本有增加适配welink等pc端的计划吗？

有没有简单的办法配置参数使插件生效，麻烦了~

**Comment by wangran99** [comment]
> 这个可能和环境有关，之前验证时没涉及这两个平台，需要配置环境来Debug

这个插件真的很有用，未来版本有增加适配welink等pc端的计划吗？

有没有简单的办法配置参数使插件生效，麻烦了~

**Comment by Zippowxk** [comment]
> > 这个可能和环境有关，之前验证时没涉及这两个平台，需要配置环境来Debug
> 
> 
> 
> 这个插件真的很有用，未来版本有增加适配welink等pc端的计划吗？
> 
> 
> 
> 有没有简单的办法配置参数使插件生效，麻烦了~

感谢朋友的认可，welink相关文档可以贴出来，我看看是什么问题

**Comment by wangran99** [comment]
> ，welink相关文档可以贴出来，我看看是什么问题

devtools确实为前端开发省了不少调试的时间，提高了效率。
devtools在welink pc上没有任何错误日志，直接不显示vue的tab。我怀疑是不是跟浏览器内核有关，谢谢。

[welink开放平台接口地址](https://open.welink.huaweicloud.com/docs/#/990hh0/whokyc/9d71zi)
[蓝信开放平台地址](https://openapi.lanxin.cn/#/fe-api/)

又打开了一下welink pc端，vue显示出来了：
![image](https://user-images.githubusercontent.com/17898332/141419967-61840332-f416-454d-909a-d8355b025037.png)
奇怪了。。。
但是蓝信pc端依然不显示vue的tab页

**Comment by wangran99** [comment]
thanks

**Comment by Zippowxk** [comment]
> thanks

不客气 感谢反馈，欢迎Star～
