### ISSUE TITLE
The code farmer pushed by Haier platform

### ISSUE THREAD

**Issue by grapecc** [Zippowxk/vue-vconsole-devtools#13]
Compare your plug-ins   to others    
for example    https://github.com/CavinHuang/vconsole-vue-devtool-plugin
What are the different advantages

**Comment by Zippowxk** [comment]
> Compare your plug-ins to others for example https://github.com/CavinHuang/vconsole-vue-devtool-plugin What are the different advantages

显然 https://github.com/CavinHuang/vconsole-vue-devtool-plugin 的作者上传了与我相同的代码，甚至相同的readme，此项目中readme还粘贴了我在掘金发布的文章内容。 目前功能的差别是 他的项目还停留在老的版本 未做更新，没有兼容Vue3 ，以及升级到最近的devtools v6

**Comment by Zippowxk** [comment]
Not  issue
