### ISSUE TITLE
通过cdn的方式引入，控制台报错

### ISSUE THREAD

**Issue by z-sq** [Zippowxk/vue-vconsole-devtools#14]
我在项目中通过cdn的方式引入
```html
<script>
      // 通过链接参数或者sessionStorage开启调试
      (function () {
        if (!/debug=true/.test(window.location) && sessionStorage.getItem('debug') !== 'true') return;
        document.write('<script src="https://unpkg.com/vconsole" onload="new window.VConsole()"><\/script>');
        document.write('<script src="https://unpkg.com/vue-vconsole-devtools" onload="window.vueVconsoleDevtools.initPlugin(VConsole.instance);"><\/script>');
      })();
</script>
```
启动项目控制台报错

```js
[Error] TypeError: null is not an object (evaluating 'l.contentWindow')
	onReady (vue_plugin.js:1:12825040)
	trigger (vue_plugin.js:1:128227)
	（匿名函数） (vconsole.min.js:10:278259)
	（匿名函数） (vconsole.min.js:10:276647)
	a (vconsole.min.js:10:274886)
```
指定vconsole@3.14.6版本无此报错；

启动vue-devtools在safari浏览器（版本16.1 ）报错：

```js
TypeError: undefined is not an object (evaluating 'browser.runtime.onMessage.addListener')
```

具体可看我的仓库https://github.com/zhang-shaoqiang/uni-app-vite.git

**Comment by Zippowxk** [comment]
收到，感谢反馈

**Comment by xch1029** [comment]
![20230321105531541](https://user-images.githubusercontent.com/20165584/226507911-60a5e5bf-a090-4f30-8b95-84d2dd515cbe.png)
![20230321105546061](https://user-images.githubusercontent.com/20165584/226507913-9254b91d-b9f3-4e29-ad0f-507aa24570ee.png)
vconsole新版本的trigger('renderTab')使用的setTimeout所导致

**Comment by Zippowxk** [comment]
感谢反馈！ 所以onReady可以也增加一个setTimeout以支持新版本，朋友你可以尝试一下 提交一个PR

**Comment by xch1029** [comment]
你可以对vconsole指定一个旧版本3.14.6   https://unpkg.com/vconsole@3.14.6/dist/vconsole.min.js

**Comment by Zippowxk** [comment]
#16 PR fix this
