### ISSUE TITLE
在Vue3项目中使用，报错：无法找到模块“vue-vconsole-devtools”的声明文件

### ISSUE THREAD

**Issue by nimohe** [Zippowxk/vue-vconsole-devtools#15]
代码：
```ts
// main.ts
import { createApp } from 'vue'
import App from './App.vue'
import VConsole from "vconsole"
import { initPlugin } from 'vue-vconsole-devtools' // 这句代码报错

import './assets/main.css'

new VConsole()
// initPlugin(new VConsole())

createApp(App).mount('#app')
```
具体的报错信息如下：
> 无法找到模块“vue-vconsole-devtools”的声明文件。“/Users/nimohe/Documents/web-space/vue3-study/ts-vue3-demo/node_modules/vue-vconsole-devtools/dist/vue_plugin.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/vue-vconsole-devtools` (如果存在)，或者添加一个包含 `declare module 'vue-vconsole-devtools';` 的新声明(.d.ts)文件ts(7016)

开发环境：
- Vue 3.2.45
- Vite 3.2.4
- vue/cli 5.0.8

**Comment by Zippowxk** [comment]
暂时没有提供TS声明文件，您可以自己在index.d.ts里声明

**Comment by nimohe** [comment]
您好，我试着新建`.d.ts`文件，这回vconsole面板中vue选项卡按钮倒是出现了，但是报错了。

## 报错提示：
```
    index.js:25 Uncaught TypeError: Cannot read properties of null (reading 'contentWindow')
    at a.onReady (index.js:25:27)
    at a.trigger (plugin.js:81:22)
    at r2._initPlugin (vconsole.min.js:10:278251)
    at r2.addPlugin (vconsole.min.js:10:278959)
    at o (index.js:64:12)
    at main.ts:10:1
```

### debug
```js
  onRenderTab(cb){
    cb(`<iframe id="vue-iframe" style="width:100%;position:absolute;top:0;bottom:0;min-height:100%;"></iframe>`);
  }
  onReady() {
    target = document.getElementById('vue-iframe') // 报错 这里target返回值是null
    targetWindow = target.contentWindow;
    target.__vdevtools__injected = true
    be.initBackendWithTargetWindow(window,targetWindow);
  }


```

## 关于TS声明文件，我试了两种方式（不确定这样写d.ts有没有问题哈）

1. 在src文件夹新建types文件夹，再新建`index.d.ts`文件
2. 在node_moudules文件夹，找到vue-vconsole-devtools -->dist --> 新建`vue_plugin.d.ts`文件（这种方式是我看其他的包，仿照来写的。）
  
代码都是
```ts
declare module 'vue-vconsole-devtools';
```

**Comment by Zippowxk** [comment]
再次感谢你的反馈，这对我很重要。先回答第二个问题，我觉得应该使用方法发一，应该避免直接修改node_modules中的文件。我觉得有几种可能性导致找不到vue-iframe，这需要调试，请问能否在codepen之类的网站复现此问题

**Comment by nimohe** [comment]
不太会操作codepen，我直接上传了一个工程文件到GitHub了。
项目地址：https://github.com/nimohe/debug-vue-vconsole-devtools

**Comment by Zippowxk** [comment]
基本已经定位到了问题，目前解决方案是 vconsole版本 写死 最大版本 3.14.6， 在3.14.7中的某项更新里 导致了此问题。所以目前请勿安装大于等于 3.14.7的vconsole版本

**Comment by nimohe** [comment]
好的，我试了一下安装 `vconsole@3.14.6`，除了在打开`vue选项卡`的时候会有一个` vue.version`报错之外（貌似是vconsole的问题，倒也不影响整体功能的使用）。
