### ISSUE TITLE
加载vue-vconsole-devtools时报错：Uncaught TypeError: Cannot read properties of null (reading 'contentWindow')

### ISSUE THREAD

**Issue by brownChan** [Zippowxk/vue-vconsole-devtools#17]
版本：
vconsole: 3.15.0
vue-vconsole-devtool: 1.0.5
谷歌浏览器: 111.0.5563.147

**问题描述：**

**加载vue-vconsole-devtools时报错：Uncaught TypeError: Cannot read properties of null (reading 'contentWindow')。**

![](https://s1.ax1x.com/2023/04/11/ppLOQ29.png)

**另外，工具可以正常打开控制台，但是想要切换“vue”tab 就会卡住。**

![](https://s1.ax1x.com/2023/04/11/ppLO8Dx.png)

**还有一个"[shared data] Master init failed"报错：**

![](https://s1.ax1x.com/2023/04/11/ppLOaPe.png)

**Comment by Zippowxk** [comment]
这个问题已经在修复中，但是还没有发版，可以使用临时方案：

> 你可以对vconsole指定一个旧版本3.14.6 https://unpkg.com/vconsole@3.14.6/dist/vconsole.min.js

详细请参考这个issue https://github.com/Zippowxk/vue-vconsole-devtools/issues/14

**Comment by brownChan** [comment]
感谢作者的帮助。
虽然用了3.14.6版本不出现“contentWindow”报错了，但是切换“vue”tab的时候还是卡住，并且控制台一直在log。截图如下：
![](https://s1.ax1x.com/2023/04/11/ppLjb34.png)

**Comment by Zippowxk** [comment]
问题反馈已收到，着手复现一下，看看是不是要更新devtools的版本了

**Comment by Zippowxk** [comment]
请问使用的vue是什么版本

**Comment by brownChan** [comment]
好的，感谢作者大大。
vue版本为 3.2.47

**Comment by Zippowxk** [comment]
更新到1.0.8修复此问题  例：https://codepen.io/zippowxk/pen/QWgpJbX

**Comment by brownChan** [comment]
没问题了，感谢作者大大，已 Star & Fork。

**Comment by Zippowxk** [comment]
感谢支持
