### ISSUE TITLE
有计划做一款基于 Eruda  的插件吗

### ISSUE THREAD

**Issue by lzpeng723** [Zippowxk/vue-vconsole-devtools#19]
Eruda 和 vconsole 类似
官网 https://github.com/liriliri/eruda

**Comment by Zippowxk** [comment]
已经在开发中

**Comment by Zippowxk** [comment]
https://github.com/Zippowxk/vue-devtools-plugin/blob/master/packages/eruda/README.md 已发布Eruda插件，
https://www.npmjs.com/package/eruda-vue-devtools?activeTab=readme
