### ISSUE TITLE
手机端浏览器打开vconsole-vue面板，一直处于loading状态

### ISSUE THREAD

**Issue by lianlinda** [Zippowxk/vue-vconsole-devtools#3]
![微信图片_20210420101126](https://user-images.githubusercontent.com/18374815/115327009-cd97c300-a1c0-11eb-95e0-e032561ae89b.jpg)

**Comment by Zippowxk** [comment]
#2 请查看这个issue，看看是否可以通过相同的方法解决

**Comment by lianlinda** [comment]
> #2 请查看这个issue，看看是否可以通过相同的方法解决

**Comment by lianlinda** [comment]
> #2 请查看这个issue，看看是否可以通过相同的方法解决

可以了

**Comment by Zippowxk** [comment]
> > #2 请查看这个issue，看看是否可以通过相同的方法解决
> 
> 可以了

好的~ 如果有用 欢迎Star
