### ISSUE TITLE
移动端vuex数据未展示，但是chrome中正常

### ISSUE THREAD

**Issue by ovenslove** [Zippowxk/vue-vconsole-devtools#5]
版本 90.0.4430.212（正式版本） (x86_64)
在chrome中能够正常展示数据
![image](https://user-images.githubusercontent.com/11400029/119292754-9450e800-bc83-11eb-9767-64dc25e8062e.png)
但是在移动端（微信，夸克）无数据
ios 14.6 wechat 8.0.6  夸克 5.0.0.1194
![image](https://user-images.githubusercontent.com/11400029/119292809-b2b6e380-bc83-11eb-9132-bc5dc73b9b34.png)

**Comment by Zippowxk** [comment]
问题收到，并已确认。正在定位问题和研究解决方案

**Comment by Zippowxk** [comment]
在分析完Vuex的初始化代码后，我发现异步加载的方式无法支持Vuex开启devtools的模式；
所以如果在非桌面Chrome平台想要调试Vuex，**只能通过同步引入的方式**，**并且一定要注意，需要在引入``./store.js``之前引入``vue-vconsole-devtools``**：
```javascript
import Vue from "vue";
import App from "./App.vue";
import VConsole from "vconsole";
import Devtools from 'vue-vconsole-devtools' //注意这行和下一行的顺序
import store from './store.js'

Devtools.initPlugin(new VConsole());
window.__VUE_DEVTOOLS_GLOBAL_HOOK__.emit("init",Vue) // 一定要添加改行

new Vue({
  store,
  render: (h) => h(App),
}).$mount("#app");

```

**Comment by Zippowxk** [comment]
不知道 有没有解决你的问题？

**Comment by Zippowxk** [comment]
如果没有问题，这个Issue我就关掉了

**Comment by Zippowxk** [comment]
在新版本devtools中，已经解决该问题，无需特殊操作
