### ISSUE TITLE
有ES5的打包版本吗

### ISSUE THREAD

**Issue by HakunaMatata052** [Zippowxk/vue-vconsole-devtools#6]
RT

**Comment by Zippowxk** [comment]
因为该项目依赖于vue-devtools工程进行打包，该包目前不支持ES5，所以目前无法支持ES5

**Comment by HakunaMatata052** [comment]
> 因为该项目依赖于vue-devtools工程进行打包，该包目前不支持ES5，所以目前无法支持ES5

能否在webpack.config.js中加入转换依赖包中的es6语法

**Comment by Zippowxk** [comment]
> > 因为该项目依赖于vue-devtools工程进行打包，该包目前不支持ES5，所以目前无法支持ES5
> 
> 能否在webpack.config.js中加入转换依赖包中的es6语法

我会试一下，单独提供

**Comment by Zippowxk** [comment]
不在计划中支持es5
