### ISSUE TITLE
未安装 Vue.js devtools 浏览器插件时需要手动初始化才能正常使用

### ISSUE THREAD

**Issue by ufologist** [Zippowxk/vue-vconsole-devtools#7]
按照官方文档的使用方法, 会一直停留在 loadig 界面

![image](https://user-images.githubusercontent.com/167221/121486984-3bfc4300-ca04-11eb-8f17-6c10154142e5.png)

尝试在 `Devtools.initPlugin` 之后执行一下 `window.__VUE_DEVTOOLS_GLOBAL_HOOK__.emit('init', Vue);` 才能成功启动

**Comment by Zippowxk** [comment]
在使用生产Vue打包代码时，确实是需要调用该方法。 使用 Vue 非生产包即可默认开启此功能，如CDN ：vue2: https://unpkg.com/vue@2.6.14   Vue3: https://unpkg.com/vue@next
