### ISSUE TITLE
项目无法打包

### ISSUE THREAD

**Issue by simondengshuaihui** [Zippowxk/vue-vconsole-devtools#8]
需求是不跟随项目打包，直接根据环境判断通过url加载进来
我想把initPlugin挂在window，打包出文件，但是打包过程中报各种错误
![image](https://user-images.githubusercontent.com/37587711/121623798-ed51b600-caa2-11eb-92eb-9cb792e64f8d.png)

**Comment by Zippowxk** [comment]
如果你期望在你的项目中打包该项目，需要参考该项目中 webpack.config.js文件

**Comment by Zippowxk** [comment]
使用CDN方式引入即可解决你的问题
