### ISSUE TITLE
插件识别不了装饰器写法的vue组件名称

### ISSUE THREAD

**Issue by simondengshuaihui** [Zippowxk/vue-vconsole-devtools#9]
vue版本2.x
Chrome 的vue-dev-tool 版本5.3.4

使用vue-property-decorator支持的TS写法，在线上环境中识别不了组件名称
`
@Component
export default class ComponentName extends Vue {}
`
具体表现为
![image](https://user-images.githubusercontent.com/37587711/123616360-ca602980-d838-11eb-826a-27c85ae723a5.png)

但是在dev本地开发环境上是可以识别的到组件名称

**Comment by simondengshuaihui** [comment]
目前有一种兼容写法在@Component 中加入name属性可以被vue-dev-tool识别到
````javascript
@Component({
  name: 'ComponentName'
})
export default class ComponentName extends Vue {}
````

**Comment by Zippowxk** [comment]
wow , 看起来是一个非常不错的临时方案，感谢分享

**Comment by Zippowxk** [comment]
已更新支持Vue3，TS兼容性更好，可能已经解决了你的问题，不妨更新一下，期待你的反馈

**Comment by jaspergg** [comment]
> 已更新支持Vue3，TS兼容性更好，可能已经解决了你的问题，不妨更新一下，期待你的反馈
无法找到模块“vue-vconsole-devtools”的声明文件。“/Users***/node_modules/vue-vconsole-devtools/dist/vue_plugin.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/vue-vconsole-devtools` (如果存在)，或者添加一个包含 `declare module 'vue-vconsole-devtools';` 的新声明(.d.ts)文件
